[nodejs]
package_manager = "pnpm"

[phases.setup]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@8.15.4 --activate"
]

[phases.build]
cmds = [
  "pnpm install --no-frozen-lockfile",
  "pnpm run build"
]
